### PR TITLE
enables in python 3 to call tox

### PR DESCRIPTION
**Pull request by ReimarBauer**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
can you explain?

i'm wondering that this still works in py27, doesn't this usually need the from future import print_function?

btw, i've prepared some milestone and the current plans are a 0.8.1 release soon with some minor updates/fixes and py27 only. Afterwards focus on py3 stuff in 0.9.0.

**Comment by ReimarBauer** [comment]
Hmm, I updated my repository after I saw that there was a change for py 2.7,  but sowehow it does not sync that pull request

**Comment by ReimarBauer** [comment]
> btw, i've prepared some milestone and the current plans are a 0.8.1 release soon with some minor updates/fixes and py27 only. Afterwards focus on py3 stuff in 0.9.0.

yes, this change was in mind as a helper for not another environment or setup for now. 

In anaconda3 the result for tox looks like

```
py27 runtests: PYTHONHASHSEED='4060337519'
py27 runtests: commands[0] | nosetests
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 723 tests in 0.270s
```

**Comment by ThomasWaldmann** [comment]
thanks for the print() details.
about NANPphone: i already fixed that, maybe rebase onto current master.

**Comment by ReimarBauer** [comment]
that is pretty good option
`git pull --rebase git@github.com:discorporate/flatland.git`

have you experience to make this the default?
`git config --global pull.rebase true`

**Comment by ThomasWaldmann** [comment]
@ReimarBauer didn't try pull/rebase yet (not manually, not as default).

**Pull request merged**
